#  ____ _____
# |  _ \_   _|  Rei Tohsaka (ichirei)
# | |_) || |    https://github.com/ichirei
# |  _ < | |
# |_| \_\|_|

add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$shell\
$time\
$line_break\
$character
"""

palette = "reitohsaka"

[palettes.reitohsaka]
blue = "#0090FF"
green = "#89E051"
red = "#D2665A"
purple = "#D69ADE"
folder = "#FFF67E"
time = "#FFD95F"

[character]
success_symbol = " [➜](green)"
error_symbol = " [✗](red)"

[directory]
format = "[ $path]($style)[$read_only]($read_only_style) "
style = "folder"
read_only_style = "red"

[fill]
symbol = " "

[shell]
zsh_indicator = " Zsh"
style = "green"
format = "[$indicator]($style) "
disabled = false

[time]
disabled = false
format = "at [ $time]($style) "
time_format = "%I:%M %p"
style = "time"

[username]
show_always = true
style_user = "blue"
style_root = "blue"
format = " []($style)[(fg:white) $user ](bg:blue fg:white)[ ]($style)"
disabled = false
aliases = { "reitohsaka" = "ReiTohsaka" }